site_name: 名校公开课程评价网
theme:
  name: material
repo_url: https://github.com/conanhujinming/comments-for-awesome-courses/
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
        custom_checkbox: true
extra:
  search:
    language: 'jp'
